"""Sphinx configuration for the convoai code-understanding library.

This builds a browsable HTML site from the 67 RST files at architecture/.

Quick start (operator):
    pip install sphinx sphinx-rtd-theme sphinxcontrib-mermaid sphinx-copybutton
    cd code_understanding/
    make html
    open _build/html/index.html
"""

# -- Project information -----------------------------------------------------

project = "convoai code understanding"
author = "Atlassian convoai team (docs auto-generated by deep investigation)"
release = "2026-05-03"

# -- General configuration ---------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinxcontrib.mermaid",   # for Mermaid diagrams in diagrams/*.rst
    "sphinx_copybutton",        # copy button on code blocks
]

source_suffix = {".rst": "restructuredtext"}
master_doc = "architecture/index"

exclude_patterns = [
    "_build",
    "**/.DS_Store",
    "**/*.bak",
]

# Treat all warnings as errors during build (catches broken refs)
# Set to False initially while there may be cross-ref issues to clean up
nitpicky = False

# -- Options for HTML output -------------------------------------------------

html_theme = "sphinx_rtd_theme"
html_theme_options = {
    "navigation_depth": 4,
    "collapse_navigation": False,
    "sticky_navigation": True,
    "titles_only": False,
}

html_static_path = ["_static"]
html_show_sourcelink = True

# -- Options for Mermaid -----------------------------------------------------

mermaid_version = "10.6.1"  # latest stable as of authoring
mermaid_init_js = "mermaid.initialize({ startOnLoad: true, theme: 'default' });"

# -- Options for copybutton --------------------------------------------------

copybutton_prompt_text = r">>> |\\$ |# "
copybutton_prompt_is_regexp = True

# -- Options for intersphinx (cross-doc linking, future) ---------------------

intersphinx_mapping = {
    # Add external doc references here as needed:
    # "python": ("https://docs.python.org/3", None),
}

# -- TODO extension settings -------------------------------------------------

todo_include_todos = True
