# Sphinx configuration for the responsible-ai-api documentation site.
#
# Theme choice: ``sphinx_rtd_theme`` is preferred for this docset because the
# audience is ops-heavy (SREs, on-call engineers, integrators) and several
# pages — notably ``api-reference`` and ``service-layer`` — carry deep,
# 3-4-level toctrees that the RTD sidebar surfaces well.
#
# Fallback: if ``sphinx_rtd_theme`` is not installed in the build
# environment, swap ``html_theme`` below to ``'alabaster'``. Alabaster
# ships with Sphinx itself (no extra install) and renders the same content
# acceptably, just with a flatter sidebar.

# -- Project information -----------------------------------------------------

project = 'responsible-ai-api'

# No pyproject.toml is checked in alongside this docset, so we fall back to
# the team-name string per the scaffold spec. If/when a pyproject.toml is
# added, prefer reading [project].authors from it instead of hardcoding.
author = 'Atlassian RAI Team'

# Hardcoded version: there is no pyproject.toml [project].version available
# at scaffold time. Bump this in lockstep with the package when one is
# added, or replace with a tomllib-based read from pyproject.toml.
version = '0.1.0'
release = version

# -- General configuration ---------------------------------------------------

extensions = [
    # autosectionlabel is essential — every prose page links to others via
    # named ``:ref:`` anchors (e.g. ``:ref:`config-overview```), and many
    # also reference section headings on the destination page.
    'sphinx.ext.autosectionlabel',
    # intersphinx is wired empty-by-default; populate ``intersphinx_mapping``
    # below when the docs need to link out to (e.g.) the Python stdlib or
    # Flask reference.
    'sphinx.ext.intersphinx',
]

# Prefix every auto-generated section label with the document name so that
# common headings ("Purpose & scope", "Documented ambiguities", "See also"
# etc., which appear on most pages) do not collide across pages.
# Note: this only affects labels generated by autosectionlabel from section
# headings; explicit anchors written as ``.. _foo:`` are unaffected and
# continue to resolve as the bare name (e.g. ``:ref:`config-overview```).
autosectionlabel_prefix_document = True

# Treat unresolved cross-references as build warnings. The build subtask
# (subtask 3) relies on this to triage missing anchors and missing pages
# without having to grep the build output for silent drops.
nitpicky = True

# Targeted nitpick suppressions. Each entry below is a forward-referenced
# anchor that is cited from existing pages (configuration.rst,
# inference-models.rst, operations.rst) and from glossary.rst, but whose
# defining page has not been authored yet. The glossary's anchor map
# (glossary.rst section "Shared Anchor Map", lines 358-688) is the
# source-of-truth registry: every entry below is tagged there as
# "forward-referenced — target page not yet authored", with the page that
# is *expected* to host the ``.. _<anchor>:`` directive.
#
# Why suppression is appropriate here (not a weakening of nitpicky=True):
#
#   * The anchors are intentional cross-references, not typos. Their
#     producer-side spelling matches the consumer-side spelling exactly
#     (verified by grepping ``:ref:`<name>``` against the anchor-map
#     rows).
#   * Removing each entry below is the *signal* that the corresponding
#     page authoring subtask has landed: when ``introduction.rst``
#     gains ``.. _introduction:`` at its top, the ``introduction`` line
#     here should be deleted in the same commit.
#   * The five page-top anchors (``introduction``, ``getting-started``,
#     ``architecture``, ``svc-moderation``, ``api-reference``) and the
#     four sub-anchors (``gs-feature-flags``, ``arch-debug-trace``,
#     ``api-etag``, ``api-debug-trace``) are the complete set of
#     forward-referenced names; any *new* ``:ref:`` warning that appears
#     post-build is therefore either a typo or a drift and should NOT be
#     added here without a glossary anchor-map entry to back it.
#
# Suppression mechanism: ``nitpick_ignore`` skips the
# "undefined label" warning for the named std-domain reference without
# changing the build output for resolved references. The tuple form is
# ``('std:ref', '<anchor>')`` — i.e. the cross-reference *type*
# (``std:ref``, the role used to cite the anchor), not the *object* type
# (``std:label``, the anchor that the role would have resolved to). This
# matches the ``f'{domain.name}:{typ}'`` key that
# ``ReferencesResolver.warn_missing_reference`` builds at warning time
# (sphinx/transforms/post_transforms/__init__.py); using ``std:label``
# silently fails to suppress and leaves every warning intact. The
# ``service-layer`` page-top anchor itself is *not* listed because
# nothing currently ``:ref:`` -cites it (only its sub-anchor
# ``svc-moderation`` is cited).
nitpick_ignore = [
    # introduction.rst — page-top anchor; cited by configuration.rst:9,
    # 2052, 2111 and glossary.rst:220, 619 (term ``RAI`` and the
    # cross-references list).
    ('std:ref','introduction'),
    # getting-started.rst — page-top anchor; cited 11× across
    # configuration.rst (180, 189, 352, 634, 2054, 2111) and
    # operations.rst (16, 405, 1004) and glossary.rst (620).
    ('std:ref','getting-started'),
    # getting-started.rst sub-anchor for the laptop-side feature-flag
    # workflow; cited from configuration.rst:2054 and glossary.rst:620.
    ('std:ref','gs-feature-flags'),
    # architecture.rst — the most-cited forward anchor (21 cites);
    # appears in every existing page (configuration, inference-models,
    # operations) plus glossary.rst.
    ('std:ref','architecture'),
    # architecture.rst sub-anchor for the global handler chain that
    # propagates ``debug_trace``; required by glossary.rst's
    # ``debug trace`` term entry (lines 76, 624) and by the cross-refs
    # list at glossary.rst:638.
    ('std:ref','arch-debug-trace'),
    # service-layer.rst sub-anchor for the four moderation services;
    # cited 11× from configuration.rst (869, 1227, 1770, 1897, 2078),
    # inference-models.rst (9, 476, 1135), and glossary.rst (122, 628).
    ('std:ref','svc-moderation'),
    # api-reference.rst — page-top anchor for the public HTTP contract;
    # cited 16× across configuration.rst, glossary.rst.
    ('std:ref','api-reference'),
    # api-reference.rst sub-anchor for the prompt-cache ETag protocol;
    # cited from configuration.rst:1068, 2066 and glossary.rst:89, 638.
    ('std:ref','api-etag'),
    # api-reference.rst sub-anchor for the debug-trace response shape;
    # required by glossary.rst's ``debug trace`` term entry (lines 76,
    # 638).
    ('std:ref','api-debug-trace'),
]

source_suffix = '.rst'
master_doc = 'index'

exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- HTML output -------------------------------------------------------------

html_theme = 'sphinx_rtd_theme'

html_static_path = ['_static']

html_theme_options = {
    # ``api-reference`` and ``service-layer`` have nested sections that go
    # 3-4 levels deep; ``navigation_depth = 4`` lets the RTD sidebar expand
    # them fully so readers can jump straight to a specific endpoint or
    # service method without first clicking into the page.
    'navigation_depth': 4,
}

# -- Intersphinx mapping -----------------------------------------------------

# Empty by default. Add entries here when the docs need to link to external
# inventories, e.g.::
#
#     intersphinx_mapping = {
#         'python': ('https://docs.python.org/3', None),
#         'flask': ('https://flask.palletsprojects.com/en/stable/', None),
#     }
intersphinx_mapping = {}
